### ISSUE TITLE
installation requirements

### ISSUE THREAD

**Issue by bpinsard** [effgarces/BookedScheduler#14]
It seems that booked is not compatible with some versions of php (8 for instance), while the readme and readme_installation mention 7 and 5.6 and above respectively.

**Comment by effgarces** [comment]
I have yet to test booked with php 8, I believe that I've tested up to 7.4, I need read what changes php8 brings to the table and test booked with it an see what will be needed to bring it up to speed.  I will keep this in mind when the time comes for a new maintenance release and while I don't know if will be able to provide php8 compatibility I can at least update the readme to let people know what versions booked currently works on.

**Comment by simonflood** [comment]
FYI development-guide.txt references yet another version of PHP, 5.3.

It's early days but I can confirm BookedScheduler 2.8.5.3 appears to work with PHP 7.4.

**Comment by effgarces** [comment]
I believe that the development-guide.txt wasn't updated in quite awhile, probably even before support for php 7 was added.
In the mean time I tested version 7.4 and seems to be working well, I'm hoping that in the coming weeks I will have some time to test version 8 and see what issues come up.

By the way thanks for the commits, I'm going over them right now, and will be merging soon after.

**Comment by bpinsard** [comment]
Found some bugs related to version 7.4
```
Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/booked/tpl_c/32065a7ae396234f77db2db15fe2c07ff3423ef4_0.file.attribute-list.tpl.php on line 103
```
seems that code is 5.x or maybe the template extension need updating?

**Comment by bpinsard** [comment]
@treborin I did flushed it multiple times, without success.

**Comment by bpinsard** [comment]
related to https://github.com/smarty-php/smarty/issues/559
Tried updating Smarty, but doesn't solve the issue.

**Comment by effgarces** [comment]
Thanks for researching this issue, it seems that we will need to add a modifier to smarty to allow this to work correctly. I went ahead and added the file, seems to work ok, but further testing is needed, check commit 012f01d
Just add the file to your install, flush the tpl_c folder and go to the attributes list.

**Comment by alexizher** [comment]
Have you thought about adding the file upload option to the list of custom attributes?

**Comment by effgarces** [comment]
No, never even crossed my mind adding a file upload option to the custom attributes. There's already an attachment functionality for the reservation, so adding it also to the custom attributes wasn't something that I had thought on doing, there's probably some cases were something like that will be useful but right now I think there are more important things to work on, unless of course someone is willing to contribute that feature.

As far as I know there isn't an official way for making the title a drop-down list, so if you need that you will need to modify your install. I have to say I'm not seeing a usage case for that .

I would ask that in the future you create a new issue or ask on gitter about these and other matters, in order to avoid discussing matters that do not relate directly to the current issue.
