### ISSUE TITLE
Reservation deletion issue in french

### ISSUE THREAD

**Issue by Thios31** [effgarces/BookedScheduler#50]
Hi,
I just update my 2.7.7 version to 2.8.5.3 but I have an issue with the deletion of a reservation.
When I click on the "Effacer" (Delete) button it doesn't work (no popup).
In english, deutch, español it works well.
I tryied to find the reason comparing some old files with new ones but nothing...
Any idea?
Thanks

PS: great to have an open source fork!

**Comment by AustinLeath** [comment]
I was able to replicate this issue

**Comment by effgarces** [comment]
Hi, I took a look at this and I believe that this issue is already fixed in the develop branch. To quickly get your install working again and from my limited testing, after updating the folder tpl/Reservation/ with the files from the develop version, my 2.8.5.3 install was working as it should using the french language.
I'm hoping that we will have a new release soon, with this and many other things fixed.

**Comment by Thios31** [comment]
Hi,
I downloaded the last developper version on last week (18/05) when I did my tests. So I have the last one.
I confirm that the delete popup doesn't appear in French.

**Comment by effgarces** [comment]
Hmmmmm, strange, when I replaced the files it started working. I need to take a closer look at this. Do you see any errors on the console (press F12)? Could you share them?

**Comment by Thios31** [comment]
I have an error when in grench mode:
![image](https://user-images.githubusercontent.com/84407564/120836559-fe13a080-c565-11eb-85e6-60e610431eb1.png)

**Comment by Thios31** [comment]
Same issue as #12 
288     [{ content: '{translate key=IAccept|escape:'javascript'} {translate key=TheTermsOfService}', styles: { fontStyle: 'bold'}},
needs double quote
288     [{ content: **"**{translate key=IAccept|escape:'javascript'} {translate key=TheTermsOfService}**"**, styles: { fontStyle: 'bold'}},

Because text include simple quotes in termsAndConditions:
J'accepte les Conditions d'Utilisation
