### ISSUE TITLE
purpose of call to sleep in the code?

### ISSUE THREAD

**Issue by bpinsard** [effgarces/BookedScheduler#66]
We noticed that call to reservation update or create are slow, running some profiling I found the following line:
https://github.com/effgarces/BookedScheduler/blob/ce1e7906227d404fe4ec5aac775ded1781919b21/lib/Application/Reservation/ReservationHandler.php#L65
Does any of you have and idea why a random sleep was put on that line? 6 seconds is pretty long. 

Searching for sleep in the repo, there are multiple instances, but this one is the worse/longer one.

Thanks

**Comment by effgarces** [comment]
Hi, yes I added that one, in commit 41d71f79dd00d0be160b47db4b897c9f2a2e1030

The issue is that there is  a racing condition in which if two or more users reserve the same resource at the exact same time then only the last one gets displays even though both succeeded in reserving the item, check here for more details:
https://forums.bookedscheduler.com/viewtopic.php?f=3&t=423

I know that this is not the ideal solution and it's only a temporary one, until I have some opening in my schedule do dedicate myself to Booked more. But seeing as we already experienced this issue I rather have this than having no fix at all. It's still possible to have a race condition but the probability is a lot lower..

**Comment by bpinsard** [comment]
Thanks for the explanation and all the work you are doing to maintain that software.
Does the duration has to be that long for the fix to work?

**Comment by effgarces** [comment]
You might not even need that line, if your website does not have many users simultaneously trying to reserve resources. You can change the value as long as you keep the randomness, it's the randomness that decreases the probability of the issue happening.
Two times? Hmmm, interesting, thanks for letting us know, from my understanding of the code, it should only be called once, I need to dive further into this.

**Comment by olivierbicler** [comment]
Sorry, but I don't understand the logic here.
I understand the aim of this fix is to avoid two users reserve the same resource at the exact same time T.
But the fix only move the problem : now, if user A reserve resource at time T (with a sleep(6) for instance) then the issue will happening with user B who :
- reserve resource at time T and also get sleep(6)
- reserve resource at time T+1 and get sleep(5)
- reserve resource at time T+2 and get sleep(4)
- reserve resource at time T+3 and get sleep(3)

I really don't get how probabilities are changed even with adding randomness, since reservations are also random (User can reserve anytime).
