### ISSUE TITLE
database upgrade.sql scripts missing

### ISSUE THREAD

**Issue by AndreZeug** [effgarces/BookedScheduler#8]
Realizing that booked is getting SaaS I found this git repository. However here the upgrade.sql scripts are not available in database_schema\upgrades\ etc. which allow to upgrade the database to newer versions. Now I am searching for the upgrade possibility from 2.7 -> 2.8.

Is there any chance to upgrade the database from 2.7 to git-master?
(I can provide upgrade.sql for 2.0 to 2.7)

**Comment by treborin** [comment]
Hi AndreZeug,

There is a file inside this zip, \database_schema\upgrades\2.8 \ schema.sql with all you need to upgrade from 2.7

**Comment by effgarces** [comment]
I just check the zip files and the repo, and you are right, in the repo there isn't a upgrade.sql, but the file is present the zip's, that's probably due to the build process that was used but I haven't investigated that yet.  In the meantime, you can use a previous release, or the latest maintenance release https://github.com/effgarces/BookedScheduler/releases/tag/2.8.5.1.
I'm due to release another one, hopefully soon, but with all that's going in the world, my schedule keeps getting messed up.

**Comment by AndreZeug** [comment]
Great, thanks a lot!
upgrade.sql from https://github.com/effgarces/BookedScheduler/releases/tag/2.8.5.1. should work for me.
Thanks for taking care of BookedScheduler!

@treborin is it correct that one can upgrade the database with schema.sql? Do you have a documentation about that?

**Comment by effgarces** [comment]
From what I what quickly seen the upgrade.sql file is simply a merged version of clean.sql, data.sql and schema.sql, so you should be able to upgrade using all of the files in sequence.

**Comment by treborin** [comment]
That's right, effgarces. I have checked it manually from 2.7.6 up to 2.8.5, and the the ony differences i see are what sql files try tu update. Using upgrade.sql against your database (2.7.6), should upgrate nicely up to 2.85.
